[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "pyhwp>=0.1b15",
    "pyinstaller>=6.18.0",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "pywebview>=6.1",
]
